### PR TITLE
Add ruby-2.7.1 to CI

### PR DESCRIPTION
**Pull request by wasabigeek**
Super early look at https://github.com/slack-ruby/slack-ruby-client/issues/321

### CODE REVIEW

**Comment by wasabigeek** [comment]
@dblock should I also add a test run with a concurrency gem?

**Comment by dblock** [comment]
> @dblock should I also add a test run with a concurrency gem?

I know nothing about this. Qu'est-ce que c'est?

**Comment by wasabigeek** [comment]
Oh I meant something like this:
```
    - rvm: 2.7.1
      env: CONCURRENCY=async-websocket
```

**Comment by dblock** [comment]
> Oh I meant something like this:
> 
> ```
>     - rvm: 2.7.1
>       env: CONCURRENCY=async-websocket
> ```

Sure why not. But let's not explode the matrix.

**Comment by wasabigeek** [comment]
Maybe I'll leave it like this? If I'm understanding correctly the non-matrix runs are for testing against ruby versions, the matrix runs are for danger / with concurrency gem

**Comment by dblock** [comment]
We can start with this, merged.

**Pull request merged**
