### PR TITLE
Update for dialogs

### PR DESCRIPTION
**Pull request by alexagranov**
We have Dialogs!!!

Note: I removed the auto-generated `spec/slack/web/api/endpoints/dialog_spec.rb` as even though it passes, it's not technically accurate due to the necessary JSON patch - plus it's tests are already included in the custom dialog_spec.rb.

### CODE REVIEW

**Comment by alexagranov** [comment]
Should I remove the auto-generated `spec/slack/web/api/endpoints/dialog_spec.rb` ?

**Comment by dblock** [comment]
👍 😮

**Comment by vbanthia** [comment]
@dblock  when is it going to be released? Any plan.

**Comment by dblock** [comment]
No plan, but I have a bit of time to work on #180 and #181, so maybe today.

**Comment by dblock** [comment]
I released 0.11.0.

**Comment by vbanthia** [comment]
Thanks :)

**Comment by arnoldmarunda** [comment]
Trying to initiate a dialog in a workflow. How do I call the dialog.open method? 
 
```
 res = $client.im_open(user: user_id)
  attachments = [{
      dialog: [{
      title: "Please provide the following details",
      callback_id: "log:dialog",
      submit_label: "Submit",
      elements: [
          {
              type: "text",
              label: "Starting Time",
              name: "started",
              value: "text",
              hint: "What time did you start work?"

          },
          {
              type: "text",
              label: "Reason",
              name: "reason",
              value: "text",
              hint: "Why were you late?"
          }
      ]
    }]
    }]

  $client.dialog_open(
    channel: res.channel.id,
    text: 'Got it. Thank you',
    attachments: attachments.to_json
  )


```

**Comment by jmanian** [comment]
You can’t spontaneously open a dialog like this. You can only open a dialog
in response to a message action (a button click or a menu selection) and
you have to use the `trigger_id` that comes along with the action payload
when you open the dialog. Check out the docs on dialogs for the full scoop.

**Comment by arnoldmarunda** [comment]
Thanks @jmanian and @alexagranov for your response, much appreciated.

 Yes, the `'request_data['trigger_id']` is coming from an interactive button payload.

I have changed the dialog as per you advice to
```
def self.log_dialog(trigger_id)
  dialog = [{
      title: "Please provide the following details",
      callback_id: "log:dialog",
      submit_label: "Submit",
      elements: [
          {
              type: "text",
              label: "Starting Time",
              name: "started",
              value: "text",
              hint: "What time did you start work?"

          },
          {
              type: "text",
              label: "Reason",
              name: "reason",
              value: "text",
              hint: "Why were you late?"
          }
      ]
    }]

  $client.dialog_open(
    trigger_id: trigger_id,
    dialog: dialog.first
  )
end
```

However, The error I am obtaining is 
`2018-01-29 12:04:08 - NoMethodError - undefined method  dialog_open for #<Slack::Web::Client:0x00000002ecb510>: `

**Comment by arnoldmarunda** [comment]
Gentlemen, the undefined method issue was due to using a lower version of 'Slack-Ruby_Client'. Was on '0.9.1' instead of at least '0.11.0'. I have upgraded to '0.11.1'. 

Everything working great. Thanks very much. However, I seemed to encounter dialog validation errors when the title was too long.
```
$client.dialog_open(
    trigger_id: trigger_id,
    dialog: {
    "callback_id": "log_form",
    "title": "Time and reason",
    "submit_label": "Submit",
    "elements": [
    {
      "type": "text",
      "label": "Started",
      "name": "started",
      "placeholder": "930am",
      "hint": "What time did you eventually start work?"
    },
    {
      "type": "text",
      "label": "Reason",
      "name": "reason",
      "placeholder": "missed the train",
      "hint": "Why were you late?"
    }
    ]
    }
  )
```

**Comment by alexagranov** [comment]
👍 Good to know there's a length limit!

**Comment by vbanthia** [comment]
Yes, there is indeed a length limit and it is very difficult to troubleshoot those issues because current ruby-client will only raise error saying `validation_errors`. It would be good to add `response_metadata` into error description. 

https://api.slack.com/methods/dialog.open

**Comment by dblock** [comment]
@vbanthia This would be useful, PR?

**Comment by vbanthia** [comment]
@dblock  https://github.com/slack-ruby/slack-ruby-client/pull/201

**Pull request merged**
