### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by technicalpickles**
This adds support for a timeout as described in https://github.com/dblock/slack-ruby-client/issues/72

Implementation is inspired by https://github.com/getsentry/raven-ruby/pull/54/files

### CODE REVIEW

**Comment by dblock** [comment]
This only affects the web client, so should be part of Slack::Web::Config.  It needs tests, README and CHANGELOG entry.

But I'd really rather not add this, but expose the connection during construction similar to how https://github.com/codegram/hyperclient does it, this way we don't have to add every option to the config. Or at least having a hash for connection options in the config so that you can throw whatever you want in there.

**Comment by technicalpickles** [comment]
I was using this branch to address timeouts I was getting from Slack, but I couldn't actually set it high enough to finish without Slack resetting the connection. I'm already working with Slack to track down what the problem is, but I'm not sure if it's a problem with the timeout as there is with file processing on their end.

**Comment by dblock** [comment]
Bump, maybe you want to try to turn this into something merge-able @technicalpickles ?

**Comment by asheynkman** [comment]
any plans to push this fix into release ? so timeout can be controlled for bigger uploads and downloads ?

**Comment by dblock** [comment]
No "plans", someone needs to finish this PR, see my comments above.

**Comment by technicalpickles** [comment]
Unfortunately it has been long enough that I don't even remember what I was using this for, and the issue I linked to is a 404 😦 

I'm going to close, but will leave the branch up if anyone wants to build on it.

**Comment by asheynkman** [comment]
hi Guys ,
 sorry been little busy did not get to this yet, I need to add respect and documentation and will created pull request. We have increase faraday timeout and that is resolve download initial connection metadata.

**Comment by dblock** [comment]
I've PRed https://github.com/slack-ruby/slack-ruby-client/pull/135 that introduces timeout options with tests and READMe.

**Pull request closed without merging**
