### PR TITLE
Add `Slack::Messages::Formatting#escape`

### PR DESCRIPTION
**Pull request by marfoldi**
Escaping control characters (`&`, `<`, and `>`) in messages as described in https://api.slack.com/reference/surfaces/formatting#escaping.

### CODE REVIEW

**Comment by dblock** [comment]
Looks like you have unrelated datastore API changes here, mind splitting them out? They will need their own CHANGELOG entry. Thanks!

**Comment by marfoldi** [comment]
> Looks like you have unrelated datastore API changes here, mind splitting them out? They will need their own CHANGELOG entry. Thanks!

Sure, I'll. Maybe it's worthwhile to update https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#update-slack-web-api as well. 😉

**Comment by dblock** [comment]
> > Looks like you have unrelated datastore API changes here, mind splitting them out? They will need their own CHANGELOG entry. Thanks!
> 
> Sure, I'll. Maybe it's worthwhile to update https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#update-slack-web-api as well. 😉

Please!

**Comment by dblock** [comment]
Merged, thanks. Care to PR the web API update?

**Comment by marfoldi** [comment]
> Merged, thanks. Care to PR the web API update?

Yess!

**Pull request merged**
