### PR TITLE
Added timeout and open_timeout options to Web API.

### PR DESCRIPTION
**Pull request by dblock**
Related to #134.

### CODE REVIEW

**Comment by macobo** [comment]
Are there any downsides to also increasing the default?

**Comment by dblock** [comment]
Faraday doesn't default the value to anything, letting the underlying Net::HTTP library handle this. I am a little wary setting it to something, but maybe I can be convinced otherwise.

**Comment by dblock** [comment]
Check out my note in README though.

**Comment by macobo** [comment]
:+1: This is definitely an improvement, thanks for fixing. 

One upside of a larger default is that if this extension is ever used in say an open-source chatbot ([pagerbot](https://github.com/stripe-contrib/pagerbot/)) having a large problem would avoid per-bot hacks and troubles for some of the larger users who try to use the bot and fail to log in.

It might be worthwhile to merge this, then reach out to some of the people having issues and figuring out if a larger but still sane baseline setting as a default would make sense.

**Comment by dblock** [comment]
I agree, we can save a lot of people debugging. What value are you using @macobo? Also are you changing only `timeout` or `open_timeout` as well?

**Comment by dblock** [comment]
Oh according to https://ruby-doc.org/stdlib-2.4.0/libdoc/net/http/rdoc/Net/HTTP.html both of these are 60 (!) seconds.

**Comment by macobo** [comment]
Sadly I don't have access to a large organization to test with, sorry!

**Pull request merged**
