### PR TITLE
Added support for cursor pagination, closes #157.

### LINKED ISSUE #157: Support pagination
https://api.slack.com/docs/pagination#cursors

This is annoying to write every time, add a pagination helper.

```ruby
    next_cursor = nil
    loop do
      response = client.users_list(presence: false, limit: 50, cursor: next_cursor)
      response.members.each do |member|
        p member.real_name
      end
      next_cursor = response.response_metadata.next_cursor
      break if next_cursor.blank?
    end
```

### PR DESCRIPTION
**Pull request by dblock**
Using the same methods you can do:

```ruby
members = []
client.users_list(presence: true, limit: 5) do |json|
  expect(json.ok).to be true
  members.concat json.members
end
```

which translates to the following in methods that support `cursor`

```ruby
Pagination::Cursor.new(self, :users_list, options).each do |page|
  yield page
end
```

### CODE REVIEW

**Comment by dblock** [comment]
@alexagranov Would love a PR and some comments pls! Iterating on docs and such now ...

**Comment by dblock** [comment]
I'll just merge it, feel free to add comments later @alexagranov ;)

**Comment by alexagranov** [comment]
Sorry @dblock, totally missed this.  Looks great!

Next time try tagging me as a Reviewer?

**Comment by dblock** [comment]
Will do, I was mostly just being impatient.

**Pull request merged**
