### PR TITLE
Fix 100% CPU usage in async examples

### PR DESCRIPTION
**Pull request by felixbuenemann**
This switches from the endless loop to accumulating and joining the threads.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Another approach would be to insert something like `sleep 0.1` into the loop, but I think this one is both more correct and more instructive, since it shows that `start_async` returns a thread.

I only tested this code with the celluloid implementation when fixing will/slacktyping#1, but the EventMachine implementation also returns a thread so it should be fine.

**Comment by felixbuenemann** [comment]
Added suggested changelog entry.

**Comment by dblock** [comment]
Thanks! Looks like build failed for something unrelated, a library upgrade, simple replacement of `post` by `POST` in the expectation. Mind fixing that here too?

**Comment by dblock** [comment]
Thanks

**Comment by dblock** [comment]
Btw, I am pretty sure I had `Thread.pass` on purpose here and not a `join`, at least in EventMachine times. If you have a moment, do actually please test the EM code?

**Pull request merged**
