### PR TITLE
Add support for block kit

### PR DESCRIPTION
**Pull request by abinoda**
Closes https://github.com/slack-ruby/slack-ruby-client/issues/251

### CODE REVIEW

**Comment by abinoda** [comment]
@dblock Since this is a major feature addition it'd be great if you could submit a release!

**Comment by gabrielmdeal** [comment]
Thanks for doing this!

FYI, this change does not make the `blocks` parameter the same first-class citizen that the `attachments` parameter is in `Slack::Web::Client` methods like `chat_postMessage`.  I'm referring to the JSON conversion and parameter validation. Instructions for how to do this are at https://github.com/slack-ruby/slack-ruby-client/blob/master/CONTRIBUTING.md#patching-slack-web-api

If you don't have the time or the need to do this, then I can follow up in a later PR.

**Comment by abinoda** [comment]
@gabrielmdeal Added a patch and updated the tests, though I just saw @JrmKrb submitted a pull request for the same 🤦‍♂️

**Comment by abinoda** [comment]
Closing in favor of https://github.com/slack-ruby/slack-ruby-client/pull/253

**Pull request closed without merging**
